### PR TITLE
Updating docker-compose.yml version to 2.1

### PR DESCRIPTION
**Pull request by PatrickLang**
This is needed per https://github.com/docker/compose/issues/4106

### CODE REVIEW

**Comment by friism** [comment]
awesome, thanks!

**Comment by PatrickLang** [comment]
Can you merge this to master? The steps in the lab at https://github.com/docker/labs/blob/master/windows/windows-containers/MultiContainerApp.md use the master branch which is still on version 2.0. That fails per https://github.com/docker/compose/issues/4106

**Comment by friism** [comment]
@PatrickLang sorry, I don't know if I messed up somehow. It should be there now: https://github.com/friism/MusicStore/blob/master/docker-compose.windows.yml

Can you confirm?

**Comment by PatrickLang** [comment]
All good. thanks!

**Pull request merged**
